config/routes.rb
Rails.application.routes.draw do

  root :to => 'reservations#home'

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :parkings
  resources :reservations
  resources :room_types
  resources :users
  resources :users_roles
  resources :statistics, only: %i(new)
  get 'statistics' , :to => 'statistics#new'
  get 'admin_reservations' , :to => 'reservations#index_admin'
  post 'statistics', :to => 'statistics#perform'

  get 'home' => "reservations#home"

end

app/views/shared/_admins_bar.html.erb
<!--<p> Admin panel </p>-->
<!--<p> <%#= link_to "Parking", parkings_path %>-->
  <%#= link_to "New room", new_room_type_path %>
  <%#= link_to "Room list", room_types_path %>
  <%#= link_to "Users list", users_path %>
<!--  <%#= link_to "Statistics", new_statistic_path %></p>-->

app/views/shared/_bottom_bar.html.erb
<div id="bottom_bar">
  <h1>Why our hotel?</h1>
    * we got plenty to offer <br>
    * free sky bar at the top of the hotel<br>
    * children will be looked after by our animators <br>
    * relax relax relax<br>
    * everything is near: theater, cinema, go-cart track (15% less if you are our guest!)<br>
</div>

app/views/shared/_top_bar.html.erb
<div id="top_bar">
  <h1> Welcome in our hotel! </h1>
</div>


<div class="nav">
  <ol>
    <li><a href="/">Home</a></li>
    <li><a href="/room_types">Rooms</a></li>


    </li>
    <% if user_signed_in? %>
      <li><%= link_to 'My reservations', reservations_path %></li>
      <% if current_user.user_role == 'admin' %>
        <li>
          <%= link_to 'Admin panel', statistics_path %>
          <ul>
            <li><%= link_to "Parking", parkings_path %></li>
            <li><%= link_to "New room", new_room_type_path %></li>
            <li> <%= link_to "Room list", room_types_path %></li>
            <li> <%= link_to "Users list", users_path %></li>
            <li> <%= link_to "All reservations", admin_reservations_path %></li>
            <li><%= link_to "Statistics", new_statistic_path %></li>
          </ul>
        </li>
      <% end %>
      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <li><a href="/users/sign_up">Sign Up</a></li>
      <li><a href="/users/sign_in">Login</a></li>
      </li>
    <% end %>
  </ol>

</div>

<div id="options">
  <% if user_signed_in? %>
    <!--    <div class="option"><%#= link_to 'Log out', destroy_user_session_path, method: :delete %></div>-->
    <div class="option_logged">Signed as: <%= current_user.first_name %> <%= current_user.last_name %>
      (<%= current_user.email %>)
    </div>
    <%# if current_user.user_role == 'admin' %>
    <!--      <div class="option">-->
    <!--        <ol>-->
    <!--          <li>-->
    <%#= link_to 'Admin panel', statistics_path %>
    <!--            <ul>-->
    <!--              <li><%#= link_to "Parking", parkings_path %></li>-->
    <!--              <li><%#= link_to "New room", new_room_type_path %></li>-->
    <!--              <li> <%#= link_to "Room list", room_types_path %></li>-->
    <!--              <li> <%#= link_to "Users list", users_path %></li>-->
    <!--              <li><%#= link_to "Statistics", new_statistic_path %></li>-->
    <!--            </ul>-->
    <!--          </li>-->
    <!--        </ol>-->
    <!--      </div>-->
    <%# end %>

    <!--    <div class="option"><%#= link_to 'My reservations', reservations_path %></div>-->
    <%# else %>
    <!--    <div class="option"><a href="/users/sign_in">Login</a></div>-->
    <!--    <div class="option"><a href="/users/sign_up">Sign Up</a></div>-->
  <% end %>
  <div id="just_space"></div>
  <!--  <div class="option"><a href="/room_types">Rooms</a></div>-->
  <!--  <div class="option"><a href="/">Home</a></div>-->
  <div style="clear:both"></div>
</div>