config/routes.rb
Rails.application.routes.draw do

  root :to => 'reservations#home'

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :parkings
  resources :reservations
  resources :room_types
  resources :users
  resources :users_roles
  resources :statistics, only: %i(new)
  get 'statistics' , :to => 'statistics#new'
  get 'admin_reservations' , :to => 'reservations#index_admin'
  post 'statistics', :to => 'statistics#perform'

  get 'home' => "reservations#home"

end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController
  before_action :set_room_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  # GET /room_types
  # GET /room_types.json
  def index
    @room_types = RoomType.all
  end

  # GET /room_types/1
  # GET /room_types/1.json
  def show
    @room_types = RoomType.all
  end

  # GET /room_types/new
  def new
    @room_type = RoomType.new
  end

  # GET /room_types/1/edit
  def edit
  end

  # POST /room_types
  # POST /room_types.json
  def create
    @room_type = RoomType.new(room_type_params)

    respond_to do |format|
      if @room_type.save
        format.html {redirect_to @room_type, notice: 'Room type was successfully created.'}
        format.json {render :show, status: :created, location: @room_type}
      else
        format.html {render :new}
        format.json {render json: @room_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /room_types/1
  # PATCH/PUT /room_types/1.json
  def update
    respond_to do |format|
      if @room_type.update(room_type_params)
        format.html {redirect_to @room_type, notice: 'Room type was successfully updated.'}
        format.json {render :show, status: :ok, location: @room_type}
      else
        format.html {render :edit}
        format.json {render json: @room_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /room_types/1
  # DELETE /room_types/1.json
  def destroy
    respond_to do |format|
      if @room_type.destroy
        format.html {redirect_to room_types_url, notice: 'Room type was successfully destroyed.'}
        format.json {head :no_content}
      else
        format.html {redirect_to room_types_url, notice: 'Can\'t be deleted. It has reservations'}
        format.json {render json: @room_type.errors, status: :unprocessable_entity}
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room_type
    @room_type = RoomType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_type_params
    params.require(:room_type).permit(:name, :cost, :max_people)
  end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper

  def rooms_for_select
    RoomType.all.collect{|m| m.name}
  end
end

app/views/room_types/_form.html.erb
<%= form_with(model: room_type, local: true) do |form| %>
  <% if room_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_type.errors.count, "error") %> prohibited this room_type from being saved:</h2>

      <ul>
      <% room_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_type_name %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost, id: :room_type_cost %>
  </div>

  <div class="field">
    <%= form.label :max_people %>
    <%= form.number_field :max_people, id: :room_type_max_people %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/room_types/edit.html.erb
<h1>Editing Room Type</h1>
<div id="text_center">
  <div id="display_inline">

<%= render 'form', room_type: @room_type %>

<%= link_to 'Show', @room_type %> |
<%= link_to 'Back', room_types_path %>
</div>
</div>

app/views/room_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Room Types</h1>
<div id="text_center">
  <div id="display_inline">
    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Cost</th>
        <th>Max people</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @room_types.each do |room_type| %>
        <tr>
          <td><%= room_type.name %></td>
          <td><%= room_type.cost %></td>
          <td><%= room_type.max_people %></td>
          <td><%= link_to 'Show', room_type %></td>
          <% if current_user.present? && current_user.user_role == 'admin' %>
            <td><%= link_to 'Edit', edit_room_type_path(room_type) %></td>
            <td><%= link_to 'Destroy', room_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

<%#= link_to 'New Room Type', new_room_type_path %>
  </div>
</div>

app/views/room_types/new.html.erb
<h1>New Room</h1>
<div id="text_center">
  <div id="display_inline">
<%= render 'form', room_type: @room_type %>

<%= link_to 'Back', room_types_path %>
  </div>
</div>

app/views/room_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> type:</strong>
  <%= @room_type.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @room_type.cost %>
</p>

<p>
  <strong>Max people:</strong>
  <%= @room_type.max_people %>
</p>
<% if current_user.present? && current_user.user_role == 'admin' %>
<%= link_to 'Edit', edit_room_type_path(@room_type) %>
<% end %>
<%= link_to 'Back', room_types_path %>