config/routes.rb
Rails.application.routes.draw do

  root :to => 'reservations#home'

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :parkings
  resources :reservations
  resources :room_types
  resources :users
  resources :users_roles
  resources :statistics, only: %i(new)
  get 'statistics' , :to => 'statistics#new'
  get 'admin_reservations' , :to => 'reservations#index_admin'
  post 'statistics', :to => 'statistics#perform'

  get 'home' => "reservations#home"

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_many :parkings, dependent: :destroy
  MAX_PERIOD_TIME = 14
  validates :valid_from, :valid_to, :room_type, presence: true
  validates :token, presence: true, uniqueness: true

  validate :room_presence
  validate :number_of_users
  validate :date_correctness
  validate :period
  validate :room_availability
  validate :parking_availability if :has_parking == '1'

  def room_type_name
    RoomType.find(room_type).name if room_type.present?
  end
  #
  # def check_room_availability
  #   if Reservation.where('room_type = ? AND valid_from <= ? AND valid_to >= ?', room_type.to_i, valid_to, valid_from).count >= RoomType::MAX_EACH_ROOM_COUNT
  #     self.errors.add(:base, "Room is not available in this period of time.")
  #   else
  #     self.errors.add(:base, "Room is available in this period of time. You can make reservation!")
  #   end
  # end

  private

  def number_of_users
    unless self.errors.any?
      if RoomType.find(room_type.to_i).max_people < num_of_user
        self.errors.add(:num_of_user, "- too many people")
      end
    end
  end

  def date_correctness
    unless self.errors.any?
      self.errors.add(:valid_from, "can't end after 'valid to'") if valid_from > valid_to
      self.errors.add(:valid_from, "can't be earlier than 6 days from now") if valid_from < Time.zone.now + 6.days
    end
  end

  def room_presence
    if room_type.to_i == 0
      self.errors.add(:room_type, "must be picked!")
    end
  end

  def period
    unless self.errors.any?
      if (valid_to - valid_from).to_i > MAX_PERIOD_TIME
        self.errors.add(:valid_from, "too long period. Max #{MAX_PERIOD_TIME} days")
      elsif valid_to == valid_from
        self.errors.add(:valid_from, "can't equals valid to")
      end
    end
  end

  def room_availability
    if Reservation.where('room_type = ? AND valid_from <= ? AND valid_to >= ?', room_type.to_i, valid_to, valid_from).count >= RoomType::MAX_EACH_ROOM_COUNT
      self.errors.add(:room_type, "is not available in this period of time.")
    end
  end

  def parking_availability
    if Parking.where('valid_from <= ? AND valid_to >= ?', valid_to, valid_from).count >= Parking::AVAILABLE_PARKING_SPOTS
      self.errors.add(:base, "All parkings are taken in this period of time.")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update, :destroy, :index, :show]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = current_user.reservations
  end

  def index_admin
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  def home
    @reservation = Reservation.new
    @max_users = RoomType.all.pluck(:max_people).max
    @number_of_users = generate_hash
    @reservations = Reservation.all
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @max_users = RoomType.all.pluck(:max_people).max
    @number_of_users = generate_hash
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = current_user.reservations.build(reservation_params)
    @max_users = RoomType.all.pluck(:max_people).max
    @number_of_users = generate_hash
    if params[:check] == 'room_availability'
      if @reservation.valid?
        redirect_to root_path, notice: 'Room is available.'
      else
        redirect_to root_path, notice: 'Room is not available.'
      end
    else
      authenticate_user!
      respond_to do |format|
        if @reservation.save
          if params['reservation']['has_parking'].to_i == 1
            parking = Parking.new(parking_params)
            parking.reservation_id = @reservation.id
            parking.save
          end
          ConfirmationMailer.with(reservation: @reservation).confirmation_email.deliver
          Delayed::Job.enqueue(MailerJob.new({reservation: @reservation}), run_at: @reservation.valid_from - 6.days )
          format.html {redirect_to @reservation, notice: 'Reservation was successfully created. Confirmation was send to your email'}
          format.json {render :show, status: :created, location: @reservation}
        else
          format.html {render :new}
          format.json {render json: @reservation.errors, status: :unprocessable_entity}
        end
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html {redirect_to @reservation, notice: 'Reservation was successfully updated.'}
        format.json {render :show, status: :ok, location: @reservation}
      else
        format.html {render :edit}
        format.json {render json: @reservation.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      ConfirmationMailer.with(reservation: @reservation).delete_confirmation_email.deliver
      format.html {redirect_to reservations_url, notice: 'Reservation was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def check_room_avability
    @ey = true
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reservation
    puts params
    @reservation = Reservation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reservation_params
    params['reservation']['token'] = SecureRandom.uuid
    params.require(:reservation).permit(:valid_from, :valid_to, :num_of_user, :has_parking, :room_type, :token)
  end

  def parking_params
    params.require(:reservation).permit(:valid_from, :valid_to)
  end

  def generate_hash
    number_hash = {}
    @max_users.times do |n|
      number_hash[n + 1] = n + 1
    end
    number_hash
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |form| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% @reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="reservation_container">
  <div class="field">
    <%= form.label :valid_from %>
    <%= form.date_field :valid_from, id: :reservation_valid_from %>
  </div>

  <div class="field">
    <%= form.label :valid_to %>
    <%= form.date_field :valid_to, id: :reservation_valid_to %>
  </div>

  <div class="selector">
    <%= form.label :num_of_user, 'How many people' %>
    <%= form.select :num_of_user, @number_of_users %>
  </div>

  <div class="selector">
    <%= form.label :room_type, 'Room type' %>
    <%= form.collection_select(:room_type, RoomType.all, :id, :name, :prompt => 'Please pick room') %>
  </div>
  <br>
  <div id="center_parking">
    <%= form.check_box :has_parking, :style => "float:left;" %>
    <%= form.label :has_parking, "Parking spot".html_safe, :style => "float:left;" %>
  </div>
  <br>
  <div class="actions">
    <%= form.button 'Check room availability' , name: "check",value: "room_availability"%>
    <%= form.submit %>
    <%= form.submit "Clear form", :type => "reset" %>
  </div>
</div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>
<div id="text_center">
  <div id="display_inline">

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>
  </div>
</div>

app/views/reservations/home.html.erb
<!--  <div id ="options">-->
    <%#= render "shared/options_bar" %>
<!--  </div>-->
<div id="text_center">
<div id="display_inline">
  <div id="sidebar">
    Contact: 517******<br>
    Email: example****@gmail.com
    <br><br>
    Reserve today!<br>

    <p id="notice"><%= flash[:notice] %></p>
    <%= render "form"%>
  </div>
</div>
</div>
<br>

<%# if user_signed_in? %>
<!--  <li><%#= link_to 'Bookings', bookings_path,class: "hvr-bounce-to-bottom" %></li>-->
<!--  <li>-->
<!--    <a class="hvr-bounce-to-bottom" ><%#= current_user.email %></a>-->
<!--  </li>-->
<!--  <li><%#= link_to 'Log out', destroy_user_session_path,class: "hvr-bounce-to-bottom", method: :delete %></li>-->

<!--  </li>-->
<%# else %>
<!--  <li><a href="/users/sign_up" class="hvr-bounce-to-bottom"> Sign Up</a></li>-->
<!--  <li><a href="/users/sign_in" class="hvr-bounce-to-bottom"> Login</a></li>-->
<%# end %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>
<div id="text_center">
  <div id="display_inline">
    <% if @reservations.present? %>
      <table>
        <thead>
        <tr>
          <th>Valid from</th>
          <th>Valid to</th>
          <th>Token</th>
          <th>User</th>
          <th>Room type</th>
          <th>Parking</th>
          <th colspan="2">Actions</th>
        </tr>
        </thead>

        <tbody>

        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.valid_from %></td>
            <td><%= reservation.valid_to %></td>
            <td><%= reservation.token %></td>
            <td><%= link_to "#{reservation.user.first_name} #{reservation.user.last_name}", user_path(reservation.user) %></td>
            <% if reservation.room_type %>
              <td><%= link_to "#{reservation.room_type_name}", room_type_path(reservation.room_type) %></td>
            <% else %>
              <td>No room type was chosen</td>
            <% end %>
            <% if reservation.has_parking %>
              <td>Yes</td>
            <% else %>
              <td>No</td>
            <% end %>
            <td><%= link_to 'Show', reservation %></td>
            <!--        <td><%#= link_to 'Edit', edit_reservation_path(reservation) %></td>-->
            <td><%= link_to 'Destroy', reservation, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <h2>No reservations found</h2>
    <% end %>
    <br>

    <%= link_to 'New Reservation', new_reservation_path %>

  </div>
</div>

app/views/reservations/index_admin.html.erb
<p id="notice"><%= notice %></p>

<h1>All Reservations</h1>
<div id="text_center">
  <div id="display_inline">
    <table>
      <thead>
      <tr>
        <th>Valid from</th>
        <th>Valid to</th>
        <th>Token</th>
        <th>User</th>
        <th>Room type</th>
        <th>Parking</th>
        <th colspan="2">Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.valid_from %></td>
          <td><%= reservation.valid_to %></td>
          <td><%= reservation.token %></td>
          <td><%= link_to "#{reservation.user.first_name} #{reservation.user.last_name}", user_path(reservation.user) %></td>
          <% if reservation.room_type %>
            <td><%= link_to "#{reservation.room_type_name}", room_type_path(reservation.room_type) %></td>
          <% else %>
            <td>No room type was choosen</td>
          <% end %>
          <% if reservation.has_parking %>
            <td>Yes</td>
          <% else %>
            <td>No</td>
          <% end %>
          <td><%= link_to 'Show', reservation %></td>
          <!--        <td><%#= link_to 'Edit', edit_reservation_path(reservation) %></td>-->
          <td><%= link_to 'Destroy', reservation, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Reservation', new_reservation_path %>

  </div>
</div>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<div id="text_center">
  <div id="display_inline">
<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>
  </div>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valid from:</strong>
  <%= @reservation.valid_from %>
</p>

<p>
  <strong>Valid to:</strong>
  <%= @reservation.valid_to %>
</p>

<p>
  <strong>Token:</strong>
  <%= @reservation.token %>
</p>

<p>
  <strong>First name:</strong>
  <%= @reservation.user.first_name %>
</p>
<p>
  <strong>Last name:</strong>
  <%= @reservation.user.last_name %>
</p>

<p>
  <strong>Room type:</strong>
  <%= link_to "#{@reservation.room_type_name}", room_type_path(@reservation.room_type) %>
</p>

<!--<%#= link_to 'Edit', edit_reservation_path(@reservation) %> |-->
<%= link_to 'Back', reservations_path %>