config/routes.rb
Rails.application.routes.draw do

  root :to => 'reservations#home'

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :parkings
  resources :reservations
  resources :room_types
  resources :users
  resources :users_roles
  resources :statistics, only: %i(new)
  get 'statistics' , :to => 'statistics#new'
  get 'admin_reservations' , :to => 'reservations#index_admin'
  post 'statistics', :to => 'statistics#perform'

  get 'home' => "reservations#home"

end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :reservation

  AVAILABLE_PARKING_SPOTS = 1
  # validate :reservation_presence
  validate :parking_params

  private

  def parking_params
    if reservation.present?
      if reservation.valid_from != valid_from || reservation.valid_to != valid_to
        self.errors.add(:base, "Dates are not correct")
      end
    end
  end
  #
  # def reservation_presence
  #   if reservation.blank?
  #     self.errors.add(:base, "There is no such reservation")
  #   end
  # end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_praking, only: [:show, :edit, :update, :destroy]

  # GET /prakings
  # GET /prakings.json
  def index
    @parkings = Parking.all
  end

  # GET /prakings/1
  # GET /prakings/1.json
  def show
  end

  # GET /prakings/new
  def new
    @parking = Parking.new
  end

  # GET /prakings/1/edit
  def edit
  end

  # POST /prakings
  # POST /prakings.json
  def create
    @parking = Parking.new(parking_params)
    @parking.reservation = Reservation.where(id: params[:parking][:reservation_id]).first

    respond_to do |format|
      if @parking.save
        @parking.reservation.has_parking = true
        @parking.reservation.save(validate: false)

        format.html { redirect_to @parking, notice: 'Parking was successfully created.' }
        format.json { render :show, status: :created, location: @parking }
      else
        format.html { render :new }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prakings/1
  # PATCH/PUT /prakings/1.json
  def update
    respond_to do |format|
      if @parking.update(parking_params)
        format.html { redirect_to @parking, notice: 'Parking was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking }
      else
        format.html { render :edit }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prakings/1
  # DELETE /prakings/1.json
  def destroy
    @parking.reservation.has_parking = false
    @parking.reservation.save(validate: false)
    @parking.destroy
    respond_to do |format|
      format.html { redirect_to parkings_url, notice: 'Parking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_praking
      @parking = Parking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_params
      params.require(:parking).permit(:valid_from, :valid_to, :reservation_id)
    end
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/parkings/_form.html.erb
<%= form_with(model: parking, local: true) do |form| %>
  <% if parking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parking.errors.count, "error") %> prohibited this parking from being saved:</h2>

      <ul>
      <% parking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valid_from %>
    <%= form.date_select :valid_from, id: :parking_valid_from %>
  </div>

  <div class="field">
    <%= form.label :valid_to %>
    <%= form.date_select :valid_to, id: :parking_valid_to %>
  </div>

  <div class="field">
    <%= form.label :reservation_id %>
    <%= form.text_field :reservation_id, id: :parking_reservation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parkings/edit.html.erb
<h1>Editing Parking</h1>

<%= render 'form', parking: @parking %>

<%= link_to 'Show', @parking %> |
<%= link_to 'Back', parkings_path %>

app/views/parkings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parkings</h1>
<div id="text_center">
  <div id="display_inline">
    <table>
      <thead>
      <tr>
        <th>Index</th>
        <th>Valid from</th>
        <th>Valid to</th>
        <th>Reservation</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @parkings.each_with_index do | parking,index| %>
        <tr>
          <td><%= index %></td>
          <td><%= parking.valid_from %></td>
          <td><%= parking.valid_to %></td>
          <td><%= link_to "#{parking.reservation.user.first_name} #{parking.reservation.user.last_name}", user_path(parking.reservation.user) %></td>
          <td><%= link_to 'Show', parking %></td>
          <td><%= link_to 'Edit', edit_parking_path(parking) %></td>
          <td><%= link_to 'Destroy', parking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Parking', new_parking_path %>

  </div>
</div>

app/views/parkings/new.html.erb
<h1>New Parking</h1>

<%= render 'form', parking: @parking %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valid from:</strong>
  <%= @parking.valid_from %>
</p>

<p>
  <strong>Valid to:</strong>
  <%= @parking.valid_to %>
</p>

<p>
  <strong>Reservation:</strong>
  <%= link_to "#{@parking.reservation.user.first_name} #{@parking.reservation.user.last_name}", user_path(@parking.reservation.user) %>
</p>

<%= link_to 'Edit', edit_parking_path(@parking) %> |
<%= link_to 'Back', parkings_path %>